
server:
  port: 9001
  
spring:
  datasource:
    url: jdbc:postgresql://database-1.cvyq3mlvbt7u.us-east-2.rds.amazonaws.com:5432/covidportal
    username: userportal
    password: passw0rd
    driver-class-name: org.postgresql.Driver
     
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false     
    hibernate:  
      ddl-auto: update
     
     
     
