# yaml stands for (YAML aint Markup Language)it uses whitespace and nesting for its properties
server:
  port: 9096
#if this was .properties spring.datasource.url = your url
# spring.datasource.username = username ... etc
spring:
  datasource:
    url: jdbc:postgresql://database-1.cyxuqcprjao8.us-east-2.rds.amazonaws.com/vaccinedb
    username: vaccineuser
    password: vaccineUser
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    hibernate:
      ddl-auto: update